version: '3.7'

networks:
  tasks-board:
    external: false
services:
  tasks-api:
    container_name: tasks-api
    image: service/tasks-api
    build: .
    environment:
      NODE_ENV: development
      DB_LOG_LEVEL: development
      PORT: 3000
      OPENAPI_FILE_PATH: ./oas3.yaml
      OPENAPI_DOCS: /docs
      OPENAPI_SPEC: /spec
      OPENAPI_ENABLE_RESPONSE_VALIDATION: true
      OPENAPI_ENABLE_REQUEST_VALIDATION: true
      DATABASE: tasks
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: tasks-db
    ports:
      - 3000:3000
    depends_on:
      - tasks-db
    networks:
      - tasks-board

  tasks-db:
    container_name: tasks-db
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - tasks-board
