openapi: 3.0.0
info:
  title: pro-tool-loan
  description: Api Web
  version: 1.0.0
servers:
  - url: http://localhost:3000/v1
    description: 'Local server'
tags:
  - name: users
    description: Users
paths:
  # USERS
  /users:
    get:
      tags:
        - users
      summary: get all users
      description: Get users based on filters
      operationId: users:get-all
      parameters:
        - name: limit
          in: query
          schema:
            type: number
            example: 0
        - name: offset
          in: query
          schema:
            type: number
            example: 0
        - name: email
          in: query
          schema:
            type: string
            example: 'xxxx@mail.com'
          'allowReserved': true
      responses:
        '200':
          description: result = drivers-api-schema
          content:
            application/json:
              schema:
                $ref: '#/components/responses/list_response'
        '400':
          description: Not found users with provided id
          content:
            application/json:
              schema:
                $ref: '#/components/responses/error'
        '403':
          description: 'Forbiden'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401_unauthorized'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/responses/404_not_found'
    post:
      tags:
        - 'users'
      summary: 'Create a new user'
      description: 'Create a new user'
      operationId: 'users:create'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users-create-one'
      responses:
        '200':
          description: 'User created'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/response'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/error'
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401_unauthorized'
        '404':
          description: 'Resource not found'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/404_not_found'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/error'
  /users/{id}:
    get:
      tags:
        - users
      summary: get user by id
      description: Get user by id
      operationId: users:get-one
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: '1'
        - name: includeTasks
          in: query
          schema:
            type: boolean
            example: true
      responses:
        '200':
          description: result = drivers-api-schema
          content:
            application/json:
              schema:
                $ref: '#/components/responses/response'
        '400':
          description: Not found users with provided id
          content:
            application/json:
              schema:
                $ref: '#/components/responses/error'
        '403':
          description: 'Forbiden'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401_unauthorized'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/responses/404_not_found'
  /tasks:
    get:
      tags:
        - tasks
      summary: get all tasks
      description: Get tasks based on filters
      operationId: tasks:get-all
      parameters:
        - name: limit
          in: query
          schema:
            type: number
            example: 0
        - name: offset
          in: query
          schema:
            type: number
            example: 0
        - name: email
          in: query
          schema:
            type: string
            example: 'mail@example.com'
      responses:
        200:
          description: result = drivers-api-schema
          content:
            application/json:
              schema:
                $ref: '#/components/responses/list_response'
    post:
      tags:
        - 'tasks'
      summary: Create a new task
      description: Create a new task
      operationId: tasks:create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tasks-create-one'
      responses:
        '200':
          description: 'Task created'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/response'
  /tasks/{id}:
    get:
      tags:
        - tasks
      summary: get task by id
      description: Get task by id
      operationId: tasks:get-one
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: '1'
        - name: includeAuthor
          in: query
          schema:
            type: boolean
            example: true

      responses:
        200:
          description: result = drivers-api-schema
          content:
            application/json:
              schema:
                $ref: '#/components/responses/response'
        400:
          description: Not found task with provided id
          content:
            application/json:
              schema:
                $ref: '#/components/responses/error'
        403:
          description: 'Forbiden'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401_unauthorized'
        404:
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/responses/404_not_found'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    #RESPONSES
    api_response:
      title: ApiResponse
      required:
        - result
        - status
      type: object
      properties:
        result:
          type: object
          description: Object according to the requested resource
        status:
          type: integer
          description: HTTP code status
          example: 200
    api_error:
      title: ApiError
      required:
        - message
        - code
      type: object
      properties:
        message:
          type: string
          description: Message that describes the error
        code:
          type: integer
          description: Code of error
        metadata:
          type: object
          description: More info of error
    list_reponse:
      title: ListResponse
      required:
        - items
        - total
      type: object
      properties:
        items:
          type: array
          items:
            type: object
          description: response elements according to the resource
        total:
          type: integer
          description: total of items saved
    api_list_reponse:
      title: ApiListResponse
      required:
        - result
        - status
      type: object
      properties:
        result:
          $ref: '#/components/schemas/list_reponse'
        status:
          type: integer
          description: HTTP code status
    users-create-one:
      title: UserCreateOne
      required:
        - email
        - password
      type: object
      properties:
        name:
          type: string
          description: User name
          example: 'John Doe'
        email:
          type: string
          description: User email
          example: 'example@test.com'
        date_of_birth:
          type: string
          description: User date of birth
          example: '1990-01-01'
        password:
          type: string
          description: User password
          example: '123456'

    ## TASKS
    tasks-create-one:
      title: TaskCreateOne
      required:
        - title
        - description
        - author_id
      type: object
      properties:
        title:
          type: string
          description: Task title
          example: 'Task 1'
        description:
          type: string
          description: Task description
          example: 'Task description'
        author_id:
          type: string
          description: User id
          example: '1'
        status:
          type: string
          description: Task status
          example: 'open'
        due_date:
          type: string
          description: Task due date
          example: '2021-01-01'

  responses:
    response:
      $ref: '#/components/schemas/api_response'
    list_response:
      $ref: '#/components/schemas/api_list_reponse'
    error:
      $ref: '#/components/schemas/api_error'
    401_unauthorized:
      $ref: '#/components/schemas/api_error'
    403_forbidden:
      $ref: '#/components/schemas/api_error'
    404_not_found:
      $ref: '#/components/schemas/api_error'
